from types import SimpleNamespace
from {{ cookiecutter.module_name }}.project_paths import project_paths

SCRIPTS = project_paths.scripts_path

configfile: SCRIPTS / 'workflow' / 'config.yaml'
config = SimpleNamespace(**config)

wildcard_constraints:

rule all:
    input:
        project_paths.reports / ...
